timeout: 5

/YamKernel
    protocol: limine
    kernel_path: boot():/boot/yamkernel.elf
    module_path: boot():/boot/wallpaper.bin
    module_path: boot():/boot/logo.bin
    module_path: boot():/boot/test_app.elf
    module_path: boot():/boot/calculator.elf
    module_path: boot():/boot/terminal.elf
    module_path: boot():/boot/browser.elf
    module_path: boot():/boot/python.elf
    module_path: boot():/boot/net_service.elf
    module_path: boot():/boot/video.elf
    module_path: boot():/boot/audio.elf
    module_path: boot():/boot/image.elf
    module_path: boot():/boot/wifi.elf
    module_path: boot():/boot/authd.elf
